// Enums as a state for entities and objects

package enums;

public enum States {
    PLAYER_STAND_STILL, PLAYER_WALK, PLAYER_NORMAL_ATTACK,
    PLAYER_SPECIAL_ATTACK, PLAYER_DEAD,
    PLAYER_JUMP_UP, PLAYER_JUMP_DOWN, PLAYER_DASH,
    OBJECT,

    MONSTER_SPAWN, MONSTER_STAND_STILL, MONSTER_WALK, MONSTER_NORMAL_ATTACK,
    MONSTER_DEAD,

    BOSS_SKILL_ONE, BOSS_SKILL_TWO, BOSS_SKILL_THREE_STAND_STILL,
    BOSS_SKILL_THREE_WALK, BOSS_JUMP_UP, BOSS_JUMP_DOWN
}
