@startuml
abstract class entities.bases.BaseEntity {
+ {static} int ATTACK_VARIATION
- int baseMaxHp
- int addMaxHp
- int currentHp
- int baseAtk
- int addAtk
- int baseDef
- int addDef
- float baseMovementSpeed
- int addMovementSpeed
- int evadeRate
- int damageIncrease
- int damageDecrease
- FaceDirection faceDirection
- Animation animation
- HitBox hitBox
- float attackRange
- String imgString
- int standStillFrames
- int walkFrames
- int normalAttackFrames
- int deadFrames
- ArrayList<Integer> frameMakeDamageNormalAttack
- boolean canTakeDamage
- boolean isDash
- float knockbackDistance
- ArrayList<Integer> dashFrame
- int dashFrameCount
- int animationWidth
- int animationHeight
- int hitBoxWidth
- int hitBoxHeight
- int hitBoxXOffset
- int hitBoxYOffset
- ArrayList<SoundLoader> soundList
- int damageReceived
+ {abstract}void setCommonStatus()
+ {abstract}void setUniqueStatus(double,double)
+ int getBaseMaxHp()
+ void setBaseMaxHp(int)
+ int getAddMaxHp()
+ void setAddMaxHp(int)
+ int getCurrentHp()
+ void setCurrentHp(int)
+ int getBaseAtk()
+ void setBaseAtk(int)
+ int getAddAtk()
+ void setAddAtk(int)
+ int getBaseDef()
+ void setBaseDef(int)
+ int getAddDef()
+ void setAddDef(int)
+ float getBaseMovementSpeed()
+ void setBaseMovementSpeed(float)
+ int getAddMovementSpeed()
+ void setAddMovementSpeed(int)
+ int getEvadeRate()
+ void setEvadeRate(int)
+ int getDamageIncrease()
+ void setDamageIncrease(int)
+ int getDamageDecrease()
+ void setDamageDecrease(int)
+ FaceDirection getFaceDirection()
+ void setFaceDirection(FaceDirection)
+ float getAttackRange()
+ void setAttackRange(float)
+ Animation getAnimation()
+ void setAnimation(Animation)
+ HitBox getHitBox()
+ void setHitBox(HitBox)
+ String getImgString()
+ void setImgString(String)
+ int getStandStillFrames()
+ void setStandStillFrames(int)
+ int getWalkFrames()
+ void setWalkFrames(int)
+ int getNormalAttackFrames()
+ void setNormalAttackFrames(int)
+ int getDeadFrames()
+ void setDeadFrames(int)
+ ArrayList<Integer> getFrameMakeDamageNormalAttack()
+ void setFrameMakeDamageNormalAttack(ArrayList<Integer>)
+ boolean canTakeDamage()
+ void setCanTakeDamage(boolean)
+ float getKnockbackDistance()
+ void setKnockbackDistance(float)
+ ArrayList<Integer> getDashFrame()
+ void setDashFrame(ArrayList<Integer>)
+ int getDashFrameCount()
+ void setDashFrameCount(int)
+ boolean isDash()
+ void setDash(boolean)
+ int getAnimationWidth()
+ void setAnimationWidth(int)
+ int getAnimationHeight()
+ void setAnimationHeight(int)
+ int getHitBoxWidth()
+ void setHitBoxWidth(int)
+ int getHitBoxHeight()
+ void setHitBoxHeight(int)
+ int getHitBoxXOffset()
+ void setHitBoxXOffset(int)
+ int getHitBoxYOffset()
+ void setHitBoxYOffset(int)
+ ArrayList<SoundLoader> getSoundList()
+ void setSoundList(ArrayList<SoundLoader>)
+ int getDamageReceived()
+ void setDamageReceived(int)
}




interfaces.Moveable <|.. entities.bases.BaseEntity
interfaces.Attackable <|.. entities.bases.BaseEntity
@enduml