@startuml
abstract class scenes.BaseScene {
- CanvasDrawer bgDrawer
- CanvasDrawer minimapDrawer
- CanvasDrawer entitiesInMiniMap
- Image bgImg
- ImageView bgImgView
- ImageView healthUI
- Rectangle healthBar
- Text healthText
- ImageView bossHealthBarFrame
- Rectangle bossHealthBar
- ImageView bossHealthBarBg
- ImageView coinUI
- Text coinText
- ImageView remainMonsterUI
- Text remainMonsterText
- Text waveText
- ImageView dashIcon
- ImageView firstIconFrame
- ImageView secondIconFrame
- Text dashRemaining
- Rectangle dashCoolDown
- ImageView specialAttackIcon
- Rectangle specialAttackCoolDown
- ImageView miniMapBgUI
- Group playerUI
- Group inventoryUI
- Group upgradeUI
- Group choiceUI
- Group perkChestUI
- int[][] lvlData
- Player player
- Set<KeyCode> pressedKeys
- Stage stage
# PlayerAnimationThread playerAnimationThread
# MovingThread movingThread
# MonsterAnimationThread monsterAnimationThread
# BotLogicThread botLogicThread
# StatThread statThread
- ArrayList<Door> doors
- boolean isPause
- ArrayList<Node> toRemovePerkIcons
+ <<Create>> BaseScene(Stage)
+ void drawUI()
- void createHpGroup()
- void createSkillIcon()
- void createFirstIcon(Image)
- void createSecondIcon(Image)
- void createDashIcon(Image)
- void createSpecialAttackIcon(Image)
- void createMiniMap()
- void createStageDetails()
- void createBossHealthBar()
- void createCoinGroup(String)
- void adjustCoinGroup(Image,double,double,double,double,double,double)
- void createMonsterRemainingGroup(String)
- void createWaveNumberGroup(String)
- void addElementsToPlayerUI()
+ void updateUI()
- void updateHpGroup()
- void updateBossHealthBar()
- void updateStageDetails()
- void updateCoin(String)
- void updateMonsterRemaining(String)
- void updateDash()
- void updateWaveNumber(String)
+ void updateMiniMap()
+ void drawBackground()
+ void createInventoryUI()
- void drawAllPerks(Group,float[],float[])
- void drawPerk(BasePerk,float,float,Group)
- void createPerkText(BasePerk,float,float,Group)
- void createPerkIcon(BasePerk,float,float,Group)
- ImageView showMiniPopUp(BasePerk,double,double)
- void pickPerkToUpgrade(BasePerk)
- void createPerkChoiceToUpgrade(BasePerk,Tier,double,double)
- void setUpChoice(ImageView,double,double,BasePerk,Tier)
- void setUpPriceGroup(ImageView,BasePerk,Group)
- Group createMenuButton()
- void addAllStats(double,ImageView,Group)
+ void createUpgradeUI()
- Group createBackButton()
+ void createPerkChestUI()
- void setPerkChestBackground(ImageView)
- void addSelectedPerksForChest(ArrayList<BasePerk>,ImageView,BaseScene)
- void selectPerkToObtain(BasePerk,BaseScene)
+ void setKey(Animation)
- void handleKeyPressed(Animation)
- void interact()
- void interactInClassSelectionScene()
- void interactInFightScene()
- void interactInMarketScene()
- void pickPerkToBuy(Symbol)
- void removePerk(Symbol)
- void activatePassingTheFloor()
- void activateJump(Animation)
- void activateDash(Animation)
- void obtainBaseReward()
- void obtainPerkChestReward()
- void pressInventory()
- void nextStage()
- void interactSymbol(Symbol)
- void pressMoveLeft(Animation)
- void pressMoveRight(Animation)
- void createOpenDoor()
- void selectClass(String)
- void setPlayerClass(String)
- void setPlayerPosition(String)
- void setFaceDirection(FaceDirection)
+ void startAllThreads(BaseScene)
- void handleKeyReleased(KeyCode,Animation)
- void releaseMoveRight(Animation)
- void releaseMoveLeft(Animation)
- void handleMouseClicked(MouseButton,Animation)
- void activateNormalAttack(Animation)
- void activateSpecialAttack(Animation)
- void handleMousePressed(MouseButton,Animation)
- void activateBowSpecialAttack(Animation)
- void activateBroadSwordSpecialAttack(Animation)
- void activateDaggerSpecialAttack(Animation)
- void handleMouseReleased(MouseButton,Animation)
+ void blink(ImageView)
+ void setScenePosition()
+ String toString()
+ void stopAllThreads()
+ void setLowBrightness()
+ void setDefaultBrightness()
+ Player getPlayer()
+ void setPlayer(Player)
+ Image getBgImg()
+ void setBgImg(Image)
+ ImageView getBgImgView()
+ void setBgImgView(ImageView)
+ Set<KeyCode> getPressedKeys()
+ int[][] getLvlData()
+ void setLvlData(int[][])
+ Stage getStage()
+ Group getPlayerUI()
+ ArrayList<Door> getDoors()
+ void setDoors(ArrayList<Door>)
+ boolean isPause()
+ void setPause(boolean)
+ ImageView getDashIcon()
+ Rectangle getDashCoolDown()
+ ImageView getSpecialAttackIcon()
+ Rectangle getSpecialAttackCoolDown()
}




javafx.scene.layout.Pane <|-- scenes.BaseScene
@enduml