@startuml
class utils.PlayerStatus {
+ {static} int START_COINS
+ {static} int MAX_PERK_OBTAIN
+ {static} int LOW_HP
+ {static} int HIGH_HP
+ {static} int LOW_ATK
+ {static} int HIGH_ATK
+ {static} int LOW_DEF
+ {static} int HIGH_DEF
+ {static} float LOW_MOVEMENT_SPEED
+ {static} float MEDIUM_MOVEMENT_SPEED
+ {static} float HIGH_MOVEMENT_SPEED
+ {static} float DAGGER_NORMAL_ATTACK_SPEED_MULTIPLIER
+ {static} float DAGGER_SPECIAL_ATTACK_SPEED_MULTIPLIER
+ {static} float BOW_NORMAL_ATTACK_SPEED_MULTIPLIER
+ {static} float BOW_SPECIAL_ATTACK_SPEED_MULTIPLIER
+ {static} float BROADSWORD_NORMAL_ATTACK_SPEED_MULTIPLIER
+ {static} float BROADSWORD_SPECIAL_ATTACK_SPEED_MULTIPLIER
+ {static} int LOW_EVADE_RATE
+ {static} int HIGH_EVADE_RATE
+ {static} int LOW_CRIT_RATE
+ {static} int HIGH_CRIT_RATE
+ {static} int LOW_CRIT_DAMAGE
+ {static} int HIGH_CRIT_DAMAGE
+ {static} int NORMAL_MAX_DASH
+ {static} int LOW_MAX_DASH
+ {static} float DEFAULT_DASH_DISTANCE
+ {static} int DEFAULT_DASH_TIME
+ {static} float DASH_COOLDOWN
+ {static} float TIME_CAN_SECOND_ATTACK
+ {static} float PLAYER_DAMAGE_COOLDOWN
}

class utils.PerkStatus {
+ {static} float PRICE_UPGRADE_PERCENT
+ {static} int PRICE_VARIATION
+ {static} int COMMON_PRICE
+ {static} int UNCOMMON_PRICE
+ {static} int RARE_PRICE
+ {static} float BERSERK_1_CRITERIA
+ {static} float BERSERK_2_1_CRITERIA
+ {static} float BERSERK_2_2_CRITERIA
+ {static} int BERSERK_1_ADDATK
+ {static} int BERSERK_2_1_ADDATK
+ {static} int BERSERK_2_2_ADDATK
+ {static} float DISCOUNT_NORMAL_FAILCHANCE
+ {static} float DISCOUNT_2_2_FAILCHANCE
+ {static} int DISCOUNT_1_DISCOUNT
+ {static} int DISCOUNT_2_1_DISCOUNT
+ {static} int DISCOUNT_2_2_DISCOUNT
+ {static} float EXTROVERT_TILES_X
+ {static} float EXTROVERT_TILES_Y
+ {static} int EXTROVERT_CRITERIA
+ {static} int EXTROVERT_1_ADDATKPERMONSTER
+ {static} int EXTROVERT_2_1_ADDATKPERMONSTER
+ {static} int EXTROVERT_2_2_ADDATKPERMONSTER
+ {static} int EXTROVERT_2_2_MINUSATKEXTRA
+ {static} int FATAL_1_ADDCRITDAMAGE
+ {static} int FATAL_2_1_ADDCRITDAMAGE
+ {static} int FATAL_2_2_ADDCRITDAMAGE
+ {static} int FATAL_2_2_MINUSCRITRATE
+ {static} int FORTIFY_1_ADDDAMAGEDECREASE
+ {static} int FORTIFY_2_1_ADDDAMAGEDECREASE
+ {static} int FORTIFY_2_2_ADDDAMAGEDECREASE
+ {static} int FORTIFY2_2_ADDATKDELAY
+ {static} float INTROVERT_TILES_X
+ {static} float INTROVERT_TILES_Y
+ {static} int INTROVERT_1_BASEADDATK
+ {static} int INTROVERT_1_MINUSADDATKPERMONSTER
+ {static} int INTROVERT_2_1_BASEADDATK
+ {static} int INTROVERT_2_1_MINUSADDATKPERMONSTER
+ {static} int INTROVERT_2_2_BASEADDATK
+ {static} int INTROVERT_2_2_MINUSADDATKPERMONSTER
+ {static} int JUKE_1_ADDEVADERATE
+ {static} int JUKE_2_1_ADDEVADERATE
+ {static} int JUKE_2_2_ADDEVADERATE
+ {static} int JUKE_2_2_MINUSDAMAGEDECREASE
+ {static} float LUCKYMAN_NORMAL_TIERCHANCE
+ {static} float LUCKYMAN_2_1_TIERCHANCE
+ {static} float LUCKYMAN_2_2_DROPCHANCE
+ {static} float PERFECTION_1_CRITERIA
+ {static} float PERFECTION_2_1_CRITERIA
+ {static} float PERFECTION_2_2_CRITERIA
+ {static} int PERFECTION_1_ADDATK
+ {static} int PERFECTION_2_1_ADDATK
+ {static} int PERFECTION_2_2_ADDATK
+ {static} int PRECISION_1_ADDCRITRATE
+ {static} int PRECISION_2_1_ADDCRITRATE
+ {static} int PRECISION_2_2_ADDCRITRATE
+ {static} int PRECISION_2_2_MINUSCRITDAMAGE
+ {static} int RAPID_NORMAL_ADDATKSPEED
+ {static} int RAPID_2_1_ADDATKSPEED
+ {static} int RAPID_2_2_ADDMOVEMENTSPEED
+ {static} int REINFORCED_1_ADDDEF
+ {static} int REINFORCED_2_1_ADDDEF
+ {static} int REINFORCED_2_2_ADDDEF
+ {static} int REINFORCED_2_2_MINUSMOVEMENTSPEED
+ {static} float THORN_NORMAL_REFLECTCHANCE
+ {static} float THORN_2_1_REFLECTCHANCE
+ {static} int THORN_2_2_SLOWTIME
+ {static} int THORN_2_2_SLOW
+ {static} float TREASURE_NORMAL_REWARDCHANCE
+ {static} float TREASURE_2_1_REWARDCHANCE
+ {static} float TREASURE_2_2_REWARDMULTIPLIER
+ {static} int UNDEAD_NORMAL_ACTIVATION
+ {static} int UNDEAD_2_1_ACTIVATION
+ {static} int UNDEAD_NORMAL_COOLDOWN
+ {static} int UNDEAD_2_2_COOLDOWN
+ {static} int UNDEAD_2_1_ADDATK
+ {static} int UNDEAD_2_1_ADDATKSPEED
+ {static} float VAMP_NORMAL_DRAINCHANCE
+ {static} float VAMP_2_2_DRAINCHANCE
+ {static} float VAMP_NORMAL_DRAINPERHIT
+ {static} float VAMP_2_1_DRAINPERHIT
}

@enduml