@startuml
class utils.ObjectStatus {
+ {static} int NOT_MOVE
+ {static} int NORMAL_ARROW_WIDTH
+ {static} int NORMAL_ARROW_HEIGHT
+ {static} int NORMAL_ARROW_SPEED
+ {static} int CHARGE_ARROW_WIDTH
+ {static} int CHARGE_ARROW_HEIGHT
+ {static} int CHARGE_ARROW_SPEED
+ {static} int MISSILE_WIDTH
+ {static} int MISSILE_HEIGHT
+ {static} int MISSILE_SPEED
+ {static} int HP_DROP_LARGE_WIDTH
+ {static} int HP_DROP_LARGE_HEIGHT
+ {static} float HP_DROP_LARGE_HEAL
+ {static} int HP_DROP_SMALL_WIDTH
+ {static} int HP_DROP_SMALL_HEIGHT
+ {static} float HP_DROP_SMALL_HEAL
+ {static} int SYMBOL_WIDTH
+ {static} int SYMBOL_HEIGHT
+ {static} int PERK_SYMBOL_WIDTH
+ {static} int PERK_SYMBOL_HEIGHT
+ {static} int COIN_REWARD_WIDTH
+ {static} int COIN_REWARD_HEIGHT
+ {static} int COIN_REWARD
+ {static} int HP_REWARD_WIDTH
+ {static} int HP_REWARD_HEIGHT
+ {static} int HP_REWARD_MAX_HP_INCREASE
+ {static} int HP_REWARD_HEAL
+ {static} int PERK_CHEST_REWARD_WIDTH
+ {static} int PERK_CHEST_REWARD_HEIGHT
+ {static} int DOOR_WIDTH
+ {static} int DOOR_HEIGHT
+ {static} int KLEE_BOMB_WIDTH
+ {static} int KLEE_BOMB_HEIGHT
+ {static} int KLEE_BOMB_HITBOX_X_OFFSET
+ {static} int KLEE_BOMB_HITBOX_Y_OFFSET
+ {static} int KLEE_BOMB_HITBOX_WIDTH
+ {static} int KLEE_BOMB_HITBOX_HEIGHT
+ {static} int BOMB_FRAMES
+ {static} int KLEE_BOMB_FRAMES_PER_SECOND
+ {static} int NUCLEAR_BOMB_WIDTH
+ {static} int NUCLEAR_BOMB_HEIGHT
+ {static} int NUCLEAR_BOMB_HITBOX_X_OFFSET
+ {static} int NUCLEAR_BOMB_HITBOX_Y_OFFSET
+ {static} int NUCLEAR_BOMB_HITBOX_WIDTH
+ {static} int NUCLEAR_BOMB_HITBOX_HEIGHT
+ {static} int NUCLEAR_BOMB_FRAMES_PER_SECOND
+ {static} int THROWER_BOMB_WIDTH
+ {static} int THROWER_BOMB_HEIGHT
+ {static} int THROWER_BOMB_ACTIVATE_WIDTH
+ {static} int THROWER_BOMB_ACTIVATE_HEIGHT
+ {static} int THROWER_BOMB_ACTIVATE_HITBOX_X_OFFSET
+ {static} int THROWER_BOMB_ACTIVATE_HITBOX_Y_OFFSET
+ {static} int THROWER_BOMB_ACTIVATE_HITBOX_WIDTH
+ {static} int THROWER_BOMB_ACTIVATE_HITBOX_HEIGHT
+ {static} int THROWER_BOMB_ACTIVATE_FRAMES
+ {static} int THROWER_BOMB_ACTIVATE_FRAMES_PER_SECOND
+ {static} int THROWER_ICE_BOMB_ACTIVATE_WIDTH
+ {static} int THROWER_ICE_BOMB_ACTIVATE_HEIGHT
+ {static} int THROWER_ICE_BOMB_ACTIVATE_HITBOX_X_OFFSET
+ {static} int THROWER_ICE_BOMB_ACTIVATE_HITBOX_Y_OFFSET
+ {static} int THROWER_ICE_BOMB_ACTIVATE_HITBOX_WIDTH
+ {static} int THROWER_ICE_BOMB_ACTIVATE_HITBOX_HEIGHT
+ {static} int THROWER_ICE_BOMB_ACTIVATE_FRAMES
+ {static} int THROWER_ICE_BOMB_ACTIVATE_FRAMES_PER_SECOND
+ {static} int STOMP_EFFECT_WIDTH
+ {static} int STOMP_EFFECT_HEIGHT
+ {static} int STOMP_EFFECT_HITBOX_X_OFFSET
+ {static} int STOMP_EFFECT_HITBOX_Y_OFFSET
+ {static} int STOMP_EFFECT_HITBOX_WIDTH
+ {static} int STOMP_EFFECT_HITBOX_HEIGHT
+ {static} int STOMP_EFFECT_FRAMES
+ {static} int STOMP_EFFECT_FRAMES_PER_SECOND
+ {static} int SHOCK_WAVE_WIDTH
+ {static} int SHOCK_WAVE_HEIGHT
+ {static} int SHOCK_WAVE_HITBOX_X_OFFSET
+ {static} int SHOCK_WAVE_HITBOX_Y_OFFSET
+ {static} int SHOCK_WAVE_HITBOX_WIDTH
+ {static} int SHOCK_WAVE_HITBOX_HEIGHT
+ {static} int SHOCK_WAVE_FRAMES
+ {static} int SHOCK_WAVE_FRAMES_PER_SECOND
+ {static} int SHOCK_WAVE_EXTRA_DAMAGE
+ {static} int FIRE_WIDTH
+ {static} int FIRE_HEIGHT
+ {static} int FIRE_HITBOX_X_OFFSET
+ {static} int FIRE_HITBOX_Y_OFFSET
+ {static} int FIRE_HITBOX_WIDTH
+ {static} int FIRE_HITBOX_HEIGHT
+ {static} int FIRE_FRAMES
+ {static} int FIRE_FRAMES_PER_SECOND
+ {static} int FIRE_EXTRA_DAMAGE
+ {static} int FIRE_TIME
+ {static} int VENDING_MACHINE_WIDTH
+ {static} int VENDING_MACHINE_HEIGHT
+ {static} int VENDING_MACHINE_FRAMES
+ {static} int VENDING_MACHINE_FRAMES_PER_SECOND
+ {static} int SHROOM_WIDTH
+ {static} int SHROOM_HEIGHT
+ {static} int SHROOM_FRAMES
+ {static} int SHROOM_FRAMES_PER_SECOND
+ {static} int MERCHANT_WIDTH
+ {static} int MERCHANT_HEIGHT
+ {static} int MERCHANT_HEAL_PERCENT
+ {static} int MIN_POTION_PRICE
+ {static} int MAX_POTION_PRICE
+ {static} ArrayList<Integer> BLACK_SMITH_WIDTH
+ {static} ArrayList<Integer> BLACK_SMITH_HEIGHT
+ {static} ArrayList<Integer> BLACK_SMITH_HITBOX_X_OFFSET
+ {static} ArrayList<Integer> BLACK_SMITH_HITBOX_Y_OFFSET
+ {static} ArrayList<Integer> BLACK_SMITH_HITBOX_WIDTH
+ {static} ArrayList<Integer> BLACK_SMITH_HITBOX_HEIGHT
+ {static} ArrayList<Integer> BLACK_SMITH_FRAMES
+ {static} ArrayList<Integer> BLACK_SMITH_FRAMES_PER_SECOND
+ {static} ArrayList<Integer> BLACK_SMITH_PAUSE_TIME
}

class utils.MonsterStatus {
+ {static} float SPAWN_TIME
+ {static} int MIN_WALKTIME
+ {static} int MAX_WALKTIME
+ {static} int MONSTER_DROP_VARIATION
+ {static} float TURNING_DELAY
+ {static} float KLEE_TURNING_DELAY
+ {static} float LOW_MOVEMENT_SPEED
+ {static} float MEDIUM_MOVEMENT_SPEED
+ {static} float HIGH_MOVEMENT_SPEED
+ {static} int LOW_EVADE_RATE
+ {static} int MEDIUM_EVADE_RATE
+ {static} float SHORT_VISION
+ {static} float MEDIUM_VISION
+ {static} float CLOSED_RANGE
+ {static} float MID_RANGE
+ {static} float LONG_RANGE
+ {static} float GIGEE_DROP_RATE
+ {static} float BOSS_DROP_RATE
+ {static} int COIN_DROP_GIGEE
+ {static} int COIN_DROP_BOSS
+ {static} int LOW_KNOCKBACK_CHANCE
+ {static} int HIGH_KNOCKBACK_CHANCE
+ {static} float LOW_KNOCKBACK_DISTANCE
+ {static} float MEDIUM_KNOCKBACK_DISTANCE
+ {static} float HIGH_KNOCKBACK_DISTANCE
+ {static} int PEASANT_HP
+ {static} int PEASANT_ATK
+ {static} int PEASANT_DEF
+ {static} float PEASANT_ATK_DELAY
+ {static} int KLEE_HP
+ {static} int KLEE_ATK
+ {static} int KLEE_DEF
+ {static} float KLEE_ATK_DELAY
+ {static} int ARCHER_HP
+ {static} int ARCHER_ATK
+ {static} int ARCHER_DEF
+ {static} float ARCHER_ATK_DELAY
+ {static} int THROWER_HP
+ {static} int THROWER_ATK
+ {static} int THROWER_DEF
+ {static} float THROWER_ATK_DELAY
+ {static} int ICE_THROWER_ATK
+ {static} int BIGBOY_HP
+ {static} int BIGBOY_ATK
+ {static} int BIGBOY_DEF
+ {static} float BIGBOY_SKILL_ONE_COOLDOWN
+ {static} float BIGBOY_COOLDOWN_AFTER_SKILL_ONE
+ {static} float BIGBOY_SKILL_TWO_COOLDOWN
+ {static} float BIGBOY_COOLDOWN_AFTER_SKILL_TWO
+ {static} float BIGBOY_SKILL_THREE_COOLDOWN
+ {static} float BIGBOY_COOLDOWN_AFTER_SKILL_THREE
+ {static} float BIGBOY_SKILL_ONE_ATTACK_RANGE
+ {static} float BIGBOY_SKILL_TWO_ATTACK_RANGE
+ {static} float BIGBOY_SKILL_TWO_JUMP_TIME
+ {static} float BIGBOY_SKILL_TWO_MAX_JUMP_DISTANCE
+ {static} int BIGBOY_SKILL_TWO_NUMBERS_OF_SHOCKWAVE
+ {static} float BIGBOY_SKILL_THREE_ATTACK_RANGE
+ {static} float BIGBOY_SKILL_THREEE_MIN_ATTACK_RANGE
+ {static} float BIGBOY_NUCLEAR_TIME
}

@enduml