@startuml
class utils.AnimationStatus {
+ {static} double SPAWN_X
+ {static} double SPAWN_Y
+ {static} int START_X
+ {static} int START_Y
+ {static} int DEFAULT_ANIMATION_WIDTH
+ {static} int DEFAULT_ANIMATION_HEIGHT
+ {static} int GAP_WIDTH
+ {static} int GAP_HEIGHT
+ {static} int DEFAULT_HITBOX_WIDTH
+ {static} int DEFAULT_HITBOX_HEIGHT
+ {static} int DEFAULT_HITBOX_X_OFFSET
+ {static} int DEFAULT_HITBOX_Y_OFFSET
+ {static} float SCALE
+ {static} int PIXEL_PER_TILE
+ {static} int MOVE_FRAME
+ {static} int ANIMATION_FRAME
+ {static} float MOVE_PER_FRAME
+ {static} float JUMP_HEIGHT
+ {static} float GRAVITY
+ {static} float GRAVITY_FOR_OBJECT
+ {static} double JUMP_VELOCITY
+ {static} int JUMP_FRAME
+ {static} ArrayList<String> DASH_AND_JUMP_WHEN_DEATH_MONSTER
+ {static} int ANONYMOUS_STAND_STILL_FRAMES
+ {static} int ANONYMOUS_WALK_FRAMES
+ {static} int BOW_STAND_STILL_FRAMES
+ {static} int BOW_WALK_FRAMES
+ {static} int BOW_NORMAL_ATTACK_FRAMES
+ {static} int BOW_SPECIAL_ATTACK_FRAMES
+ {static} int BOW_DASH_FRAME
+ {static} int BOW_DEAD_FRAMES
+ {static} int BOW_SPECIAL_ATTACK_CHARGE_TIME
+ {static} float BOW_SPECIAL_ATTACK_COOLDOWN
+ {static} int BOW_SPECIAL_ATTACK_DAMAGE
+ {static} int BOW_SPECIAL_ATTACK_DAMAGE_INCREASE_PER_FRAME
+ {static} int BOW_SPECIAL_ATTACK_MAX_DAMAGE_INCREASE
+ {static} int BROADSWORD_STAND_STILL_FRAMES
+ {static} int BROADSWORD_WALK_FRAMES
+ {static} int BROADSWORD_NORMAL_ATTACK_FRAMES
+ {static} int BROADSWORD_SPECIAL_ATTACK_FRAMES
+ {static} int BROADSWORD_DASH_FRAMES
+ {static} int BROADSWORD_DEAD_FRAMES
+ {static} int BROADSWORD_ANIMATION_WIDTH
+ {static} int BROADSWORD_ANIMATION_HEIGHT
+ {static} int BROADSWORD_HITBOX_WIDTH
+ {static} int BROADSWORD_HITBOX_HEIGHT
+ {static} int BROADSWORD_HITBOX_X_OFFSET
+ {static} int BROADSWORD_HITBOX_Y_OFFSET
+ {static} int BROADSWORD_SPECIAL_ATTACK_JUMP_HEIGHT
+ {static} float BROADSWORD_SPECIAL_ATTACK_COOLDOWN
+ {static} int BROADSWORD_SPECIAL_ATTACK_DAMAGE
+ {static} int DAGGER_STAND_STILL_FRAMES
+ {static} int DAGGER_WALK_FRAMES
+ {static} int DAGGER_NORMAL_ATTACK_FRAMES
+ {static} int DAGGER_SPECIAL_ATTACK_FRAMES
+ {static} int DAGGER_DASH_FRAMES
+ {static} int DAGGER_DEAD_FRAMES
+ {static} float DAGGER_SPECIAL_ATTACK_WARP_DISTANCE
+ {static} float DAGGER_SPECIAL_ATTACK_COOLDOWN
+ {static} int DAGGER_SPECIAL_ATTACK_DAMAGE
+ {static} int DAGGER_SPECIAL_ATTACK_CRIT_CHANCE
+ {static} float DAGGER_SPECIAL_ATTACK_CRIT_BUFF_DURATION
+ {static} int SPAWN_FRAMES
+ {static} int PEASANTGIGEE_STAND_STILL_FRAMES
+ {static} int PEASANTGIGEE_WALK_FRAMES
+ {static} int PEASANTGIGEE_NORMAL_ATTACK_FRAMES
+ {static} int PEASANTGIGEE_DEAD_FRAMES
+ {static} int KLEEGIGEE_STAND_STILL_FRAMES
+ {static} int KLEEGIGEE_WALK_FRAMES
+ {static} int KLEEGIGEE_NORMAL_ATTACK_FRAMES
+ {static} int KLEEGIGEE_DEAD_FRAMES
+ {static} int KLEEGIGEE_SPEED_INCREASE
+ {static} float KLEEGIGEE_BOMB_TIME
+ {static} int ARCHERGIGEE_STAND_STILL_FRAMES
+ {static} int ARCHERGIGEE_WALK_FRAMES
+ {static} int ARCHERGIGEE_NORMAL_ATTACK_FRAMES
+ {static} int ARCHERGIGEE_DEAD_FRAMES
+ {static} int THROWERGIGEE_STAND_STILL_FRAMES
+ {static} int THROWERGIGEE_WALK_FRAMES
+ {static} int THROWERGIGEE_NORMAL_ATTACK_FRAMES
+ {static} int THROWERGIGEE_DEAD_FRAMES
+ {static} int THROWERGIGEE_HITBOX_WIDTH
+ {static} int THROWERGIGEE_HITBOX_X_OFFSET
+ {static} float THROWERGIGEE_THROW_TIME
+ {static} int ICETHROWERGIGEE_STAND_STILL_FRAMES
+ {static} int ICETHROWERGIGEE_WALK_FRAMES
+ {static} int ICETHROWERGIGEE_NORMAL_ATTACK_FRAMES
+ {static} int ICETHROWERGIGEE_DEAD_FRAMES
+ {static} float ICETHROWERGIGEE_THROW_TIME
+ {static} int ICETHROWERGIGEE_SLOW_AMOUNT
+ {static} int ICETHROWERGIGEE_MAX_SLOW_AMOUNT
+ {static} int ICETHROWERGIGEE_SLOW_DURATION
+ {static} int BIGBOY_STAND_STILL_FRAMES
+ {static} int BIGBOY_WALK_FRAMES
+ {static} int BIGBOY_SKILL_ONE_FRAMES
+ {static} ArrayList<Integer> BIGBOY_SKILL_ONE_FRAMES_HOLD
+ {static} float BIGBOY_SKILL_ONE_ANIMATION_SPEED
+ {static} int BIGBOY_SKILL_TWO_FRAMES
+ {static} ArrayList<Integer> BIGBOY_SKILL_TWO_FRAMES_HOLD
+ {static} float BIGBOY_SKILL_TWO_ANIMATION_SPEED
+ {static} int BIGBOY_SKILL_THREE_STAND_FRAMES
+ {static} int BIGBOY_SKILL_THREE_WALK_FRAMES
+ {static} int BIGBOY_DEAD_FRAMES
+ {static} int BIGBOY_ANIMATION_WIDTH
+ {static} int BIGBOY_ANIMATION_HEIGHT
+ {static} int BIGBOY_HITBOX_WIDTH
+ {static} int BIGBOY_HITBOX_HEIGHT
+ {static} int BIGBOY_HITBOX_X_OFFSET
+ {static} int BIGBOY_HITBOX_Y_OFFSET
}

@enduml